#版本升级表
CREATE TABLE `version_upgrade` (
`id` SMALLINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
`app_id` SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '客户端设备ID',
`version_id` SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '大版本号ID',
`version_mini` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '小版本号',
`version_code` VARCHAR(10) DEFAULT NULL COMMENT '版本标识 1.2',
`type` TINYINT(2) UNSIGNED DEFAULT NULL  COMMENT '是否升级 0不升级，1升级，2强制升级',
`apk_url` VARCHAR(255) DEFAULT NULL,
`upgrade_point` VARCHAR(255) DEFAULT NULL COMMENT '升级提示',
`status` TINYINT(2) DEFAULT NULL,
`create_time` INT(11) DEFAULT NULL,
`update_time` INT(11) DEFAULT NULL,
PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `app` (
`id` SMALLINT(4) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
`name` VARCHAR(10) DEFAULT NULL COMMENT 'APP类型名称',
`is_encryption` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否加密 0不加密，1加密',
`key` VARCHAR(20) NOT NULL DEFAULT '0' COMMENT '加密key',
`image_size` TEXT COMMENT '按json_encode存储',
`create_time` INT(11) NOT NULL COMMENT '创建时间',
`update_time` INT(11) NOT NULL COMMENT '更新时间',
`status` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '状态 1正常，2删除',
PRIMARY KEY (`id`)
)ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
#客户端错误信息记录表
CREATE TABLE `error_log`(
`id` SMALLINT(4) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
`app_id` SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '客户端设备ID',
`did` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '客户端设备号',
`version_id` SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '大版本号ID',
`version_mini` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '小版本号',
`error_log` TEXT COMMENT '错误日志信息',
`create_time` INT(11) NOT NULL COMMENT '创建时间',
`update_time` INT(11) NOT NULL COMMENT '更新时间',
`status` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '状态 1正常，2删除',
PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;